version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - mvn clean install
  build:
    commands:
      - echo "Building the application..."
      - mvn package
  post_build:
    commands:
      - echo "Build completed!"
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
